package cgcdb;

public class CATEGORY_MAIN_3G extends CATEGORY_MAIN_2G3GLTE{
	
	public CATEGORY_MAIN_3G(
			String IDENTIFY_CATEGORY,
			String CATEGORY_TYPE,
			String INTERIMS_VERSION,
			String TABLE_SPEC,
			String TABLE_ID,
			String TABLE_DESC,
			String TESTBAND){
		this.IDENTIFY_CATEGORY = IDENTIFY_CATEGORY;
		this.CATEGORY_TYPE = CATEGORY_TYPE;
		this.INTERIMS_VERSION = INTERIMS_VERSION;
		this.TABLE_SPEC = TABLE_SPEC;
		this.TABLE_ID = TABLE_ID;
		this.TABLE_SPEC = TABLE_SPEC;
		this.TESTBAND = TESTBAND;
	}
}
