package cgcdb;

public class CATEGORY_DETAIL_LTE extends CATEGORY_DETAIL_2G3GLTE{
	public CATEGORY_DETAIL_LTE(){
			
		}
		
		public CATEGORY_DETAIL_LTE(
				String IDENTIFY_CATEGORY_D,
				String IDENTIFY_CATEGORY,
				String RELEASE,
				String CATEGORY_FDD_TYPE,
				String CATEGORY,
				String VALID_PALTFORM){
			this.IDENTIFY_CATEGORY_D = IDENTIFY_CATEGORY_D;
			this.IDENTIFY_CATEGORY = IDENTIFY_CATEGORY;
			this.RELEASE = RELEASE;
			this.CATEGORY_FDD_TYPE = CATEGORY_FDD_TYPE;
			this.CATEGORY = CATEGORY;
			this.VALID_PALTFORM = VALID_PALTFORM;
		}
}
